# ./Dockerfile
# Extended from the official Elixir image
FROM elixir:1.20

RUN apt-get update -y
RUN apt-get install -y build-essential inotify-tools postgresql-client git curl && apt-get clean

# replace shell with bash so we can source files
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

# Install hex package manager
RUN mix local.hex --force
RUN mix local.rebar --force

# copy shellscript to run with docker-compose
COPY entrypoint.sh ./
# make shellscript executable
RUN chmod +x ./entrypoint.sh

# Install Phoenix Framework
RUN mix archive.install hex phx_new --force

# Setup Phoenix as basic API server
RUN yes | mix phx.new yic2 --no-html --no-assets --no-dashboard --no-live

WORKDIR /yic2